name = "supaflare-worker"
type = "webpack"
route = ''
account_id = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-10"
webpack_config = "webpack.config.js"
kv_namespaces = [ 
  { binding = "SUPAFLARE", id = "b015780fa2f04f369e827ea87e0ee289" }
]
