name = "supaflare-worker"
type = "webpack"
route = ''
account_id = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-07-07"
webpack_config = "webpack.config.js"
kv_namespaces = [ 
  { binding = "SUPAFLARE", id = "8bd0d0fddbd44f3199e78333f51ff994" }
]
